# Generated by Django 4.2 on 2024-05-16 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('desafioadl', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtarea',
            old_name='eliminada',
            new_name='estado',
        ),
        migrations.AlterField(
            model_name='subtarea',
            name='descripcion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='subtarea',
            name='tarea_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtareas', to='desafioadl.tarea'),
        ),
    ]
